[package]
name = "rate"
version = "0.1.0"
authors = ["Johannes Altmanninger <aclopte@gmail.com>"]
description = "DRAT proof checker for DIMACS formulas"
edition = "2018"
license = "MIT"

[dependencies]
memmap = "*"
ansi_term = "*"
derive_more = "*"
clap = "*"
scopeguard = "*"
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.3", optional = true }
cpuprofiler = { version = "0.0.3", optional = true }

[features]
default = []
fast = []
flame_it = ["flame", "flamer"]
profile_it = ["cpuprofiler"]

[profile.release]
panic = "abort"
