[package]
name = "rate"
version = "0.1.0"
authors = ["Johannes Altmanninger <aclopte@gmail.com>"]
description = "DRAT proof checker for DIMACS formulas"
edition = "2018"
license = "MIT"

[dependencies]
rate-macros = { path = "rate-macros" }
ansi_term = "0.11"
derive_more = "0.13"
clap = "2.32"
scopeguard = "0.3"
multimap = "0.4"
flame = { version = "0.2", optional = true }
flamer = { version = "0.3", optional = true }
atty = "0.2"
static_assertions = "0.3"
bitfield = "0.13"
memmap = "0.7"

[features]
default = []
flame_it = ["flame", "flamer"]
clause_lifetime_heuristic = []

[profile.release]
panic = "abort"
