#!/bin/sh

set -e -u

cnf="$(realpath "$1")"
shift
lrat="$(realpath "$1")"
shift

cnf_without_comments="$(realpath "$(mktemp lrat-check.XXXXXXX)")"

cleanup() {
    rm "$cnf_without_comments"
    exit 1
}
trap cleanup INT TERM

grep -v '^c' "$cnf" | grep -v '^$' > "$cnf_without_comments"

set +e
printf '(lrat-check "%s" "%s")' "$cnf_without_comments" "$lrat" | /usr/local/bin/check-lrat
status="$?"
rm "$cnf_without_comments"
exit "$status"
