[package]
name = "rate-macros"
version = "0.1.0"
authors = ["Johannes Altmanninger <aclopte@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"